### PR TITLE
El7 journal

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@anders-larsson Do you run any rsyslog servers on EL7? I would be curious to see how this performs there. If you're using this module on any log server, would you be able to test that this PR does not break anything?

@joshuabaird Could you also test and let me know how it goes? Want to be sure this is all good before we merge.

**Comment by ghoneycutt** [comment]
Released in v0.23.0

**Comment by joshuabaird** [comment]
Thank you!  Sorry I wasn't around this weekend to help you test.

**Comment by anders-larsson** [comment]
@ghoneycutt Sorry that I'm too late to respond to this issue. We've seen similar issues on RHEL7 but in our case it does log locally but log messages never finds their way to the remote server. Only a rsyslog service restart restores the remote logging functionality.

I'll give v0.23.0 a try and see if it helps for that issue as well.

**Comment by joshuabaird** [comment]
@ghoneycutt Any plans to release 0.23 to Forge?

**Comment by ghoneycutt** [comment]
Sure.

https://forge.puppetlabs.com/ghoneycutt/rsyslog/0.23.0

**Comment by joshuabaird** [comment]
Ugh - I'm actually seeing some potential issues now that I re-test this.  I'm looking into it now.

**Comment by joshuabaird** [comment]
So, I'm seeing issues when applying this code to RHEL7 systems that didn't previously have the imjournal config.  I can't get anything to log to files (eg, /var/log/messages).  A restart of the service doesn't fix it, but a reboot does (something with systemd?). 

@anders-larsson Would you mind checking to see if you see the same behavior on your EL7 hosts?

**Comment by anders-larsson** [comment]
@joshuabaird I'll check tomorrow when I'm back at work.

**Comment by anders-larsson** [comment]
@joshuabaird I haven't found any EL7 systems in our environment having problem logging locally to files in /var/log without the imjournal configuration.

Applying the changes released in 0.23 throws a lot of old messages into /var/log/messages. I suppose the messages come from systemd's journal? However new messages seems to be ignored. I used the logger utility to attempt to create entries in /var/log/messages but nothing shows up.

Last entry in messages is rsyslogd rate-limiting messages from imjournal. As you stated restarting rsyslog does not help but rebooting the whole system does solve it.

**Comment by joshuabaird** [comment]
@anders-larsson Ok - so we are seeing the exact same thing.  However, I did have EL7 systems that were not logging locally to /var/log without the imjournal config (some were, some were not; it may have had something to do with the volume of logs).

Yeah, I think the old messages come from the journal which is expected behavior from what I understand.  I'm not exactly sure why new messages to /var/log go missing.  Even more puzzling is why it requires a reboot and not just a restart of rsyslogd.

In any case, I'm not sure there is much we can do about this.  The "proper" configuration for EL7 is to enable imjournal, so this may just be something we have to live with?

**Comment by anders-larsson** [comment]
If it as you said that this is something that should be present on all EL7 systems we need to get it implemented somehow. It would be great if we could find a workaround the whole "restarting system" part because that's not really feasible.

From http://www.rsyslog.com/doc/v8-stable/configuration/modules/imjournal.html. See link for full context though. But if it's enabled as a default setting in EL we should probably keep it enabled.
 **It is strongly recommended to use this plugin only if there is hard need to do so.**

BTW I suppose the messages we see in /var/log/messages are from other sources than systemd's journal and that's why we see things showing up there.

**Comment by joshuabaird** [comment]
Yeah, to confirm, imjournal is enabled by default on all EL7 systems.  I agree, I wish there was a solution to the reboot.  I'll do some digging today.

Here is a RH article which discusses this:
https://access.redhat.com/solutions/2112651?tour=6

**Comment by joshuabaird** [comment]
Ok - the problem is that ```/dev/log``` is missing when the system is in this state.

To recreate, you can run ```systemctl restart systemd-journald.socket```  After this, ```/dev/log``` is recreated and logging works as expected.  I'm not sure if this is something that should be included in this module or not.  

@ghoneycutt @anders-larsson thoughts?

**Comment by ghoneycutt** [comment]
Yes, we should do it only on EL7 and have a param that defaults to true so that it is done conditionally. If someone does not want the behavior, they can set the param and it would skip managing /dev/log

**Comment by ghoneycutt** [comment]
Really appreciate you two coming together and figuring this all out. Much thanks!

**Comment by anders-larsson** [comment]
I agree with @ghoneycutt. We should add logic to restart systemd-journald.socket if necessary on EL7 systems.

**Pull request merged**
