### PR TITLE
Devlog

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by joshuabaird** [comment]
Thanks! :+1:

**Comment by ghoneycutt** [comment]
Looks good though a few jobs failed because of timeouts to github. Re-running those.

**Comment by ghoneycutt** [comment]
Released in v0.24.0

Thanks @joshuabaird !!

**Comment by joshuabaird** [comment]
Can you release to Forge when you get time, please?

**Comment by joshuabaird** [comment]
@ghoneycutt Could you please release to Forge when you get a chance?  Thanks!

**Comment by ghoneycutt** [comment]
https://forge.puppetlabs.com/ghoneycutt/rsyslog/0.24.0

Please rate it if you have not already :)

**Comment by joshuabaird** [comment]
Thanks, and rated!

**Pull request merged**
