### PR TITLE
Align with the RHEL7 defaults.

### PR DESCRIPTION
**Pull request by gothicx**
The ".so" is not required for default modules to load.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Has this always been the case? That portion supports rsyslog > v2

**Comment by ghoneycutt** [comment]
@anders-larsson What's your oldest version of rsyslog? We should document that in the README under compatibility. It would also help here to understand how far back we need to support as the configuration changes between versions.

**Comment by anders-larsson** [comment]
@ghoneycutt It works correctly without the 'so' extension on the earliest version we're managing at our location. I'll have to ask the other locations if they're using earlier versions than us though just in case.

Removing the 'so' extension made rsyslog print the following lines to logs. I'm not sure if it's relevant though. It did not show up after returning to the previous configuration and restarting the service.

```
rsyslogd: WARNING: rsyslogd is running in compatibility mode. Automatically generated config directives may interfer with your rsyslog.conf settings. We suggest upgrading your config and adding -c3 as the first rsyslogd option.
rsyslogd: Warning: backward compatibility layer added to following directive to rsyslog.conf: ModLoad immark
rsyslogd: Warning: backward compatibility layer added to following directive to rsyslog.conf: MarkMessagePeriod 1200
rsyslogd: Warning: backward compatibility layer added to following directive to rsyslog.conf: ModLoad imuxsock
```

**Comment by Phil-Friderici** [comment]
@ghoneycutt our old SLES 10 system with the old rsyslog have been decommissioned :)

**Comment by ghoneycutt** [comment]
Thank you!

**Pull request merged**
