### PR TITLE
Deprecate lsbmajdistrelease in favour of operatingsystemrelease

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Use inheritance for :facts in spec tests

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
For detailed osfamily related facts have a look at this repo:
https://github.com/petems/rspec-puppet-facts

**Comment by Phil-Friderici** [comment]
PS: most changes in spec/classes/init_spec.rb are related to different indenting needed to activate inheritance. Second most changes are related to remove now obsolete :facts definitions.

**Comment by ghoneycutt** [comment]
Thank you!

**Comment by ghoneycutt** [comment]
Released in v0.21.0

**Pull request merged**
