### PR TITLE
Add Suse 12 support

### PR DESCRIPTION
**Pull request by anders-larsson**
File 'sysconfig.suse12.erb' is the stock version of /etc/sysconfig/syslog with the comment (#) removed from the 'RSYSLOGD_PARAMS' line. rsyslog is started with '-n' as argument in either case.

### CODE REVIEW

**Comment by anders-larsson** [comment]
@ghoneycutt What's needed for this request to be merged? Are we waiting for a rebase?

**Comment by ghoneycutt** [comment]
This was waiting on #61 to be merged, which I just did and released as v0.14.0. It now needs to be rebased and tested.

**Comment by anders-larsson** [comment]
@ghoneycutt I've rebased the changes and verified it on the following versions:
`````
2.0.6
3.18.3
3.22.1
4.2.0
4.6.2
5.10.1
5.8.10
5.8.6
5.8.7
7.4.7
8.4.0
`````

**Comment by ghoneycutt** [comment]
Hi @anders-larsson 

The code shows that it supports rsyslog v2, 3 and 5, though your testing shows it also work with v4, 7 and 8. Shouldn't we change the code around here[1] to show that?

I think it is safe to safe we support rsyslog v2-8, would you agree?

[1] - https://github.com/ghoneycutt/puppet-module-rsyslog/pull/57/files#diff-60ae41fd0a31977447947f59940ee9a4L65

**Comment by ghoneycutt** [comment]
Oh and thanks again for taking the time to rebase and see this through, I appreciate it!

**Comment by anders-larsson** [comment]
Agreed. We should be able change that line to all versions between version 2 and 8. I found an issue with logrotate and SLES12 (or actually systemd) since /etc/init.d/rsyslog doesn't exist anymore with systemd. We could change '/etc/init.d/syslog reload > /dev/null' with 'service syslog reload > /dev/null'. I've verified that it works on SLES 10.{2,3,4} and SLES 11.{0.1.2.3} and finally SLES12. Otherwise we'll need to add a specific code path for SLES 12.

**Comment by Phil-Friderici** [comment]
@anders-larsson good point. I would also prefer to switch to 'service syslog reload'.

**Comment by anders-larsson** [comment]
I've amended my previous change with the changes we've mentioned. Please verify it looks OK. Would be awesome if someone could test it as well since it actually does quite a few changes to the module.

However it doesn't work to define rsyslog_conf_version as an integera in hiera at the moment. It can only be sent to the module as an string. I'm not really a fan of converting everything to strings just to convert it back to an integer in the class. What's your suggestion?

**Comment by ghoneycutt** [comment]
Ugh.. we have to support strings in Hiera. On the brighter side, I think that the way strings work in Puppet/Ruby, it should *just work*. :)

**Comment by anders-larsson** [comment]
>Ugh.. we have to support strings in Hiera. On the brighter side, I think that the way strings work in Puppet/Ruby, it should just work. :)

Strings does work. However giving an integer input in hiera does not. Is it supported to supply integers to classes in hiera?

**Comment by ghoneycutt** [comment]
I meant that you have to assume people will use strings in Hiera

**Comment by ghoneycutt** [comment]
@anders-larsson how's it coming with this?

**Comment by Phil-Friderici** [comment]
@ghoneycutt the code support strings. It expect the user to pass the strings 'USE_DEFAULTS' or '2' to '8' into $rsyslog_conf_version. What did we miss here ?

**Comment by ghoneycutt** [comment]
Looks good, just needs a rebase

**Comment by Phil-Friderici** [comment]
feasible ;)

**Comment by anders-larsson** [comment]
Rebased! :)

**Pull request merged**
