### PR TITLE
deprecate type(), add spec tests for $logrotate_present

### PR DESCRIPTION
**Pull request by Phil-Friderici**
requieres stdlib >= 4.2.0 for is_bool()

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
I also checked the array handling in erb files. Found no place where a string might get to an .each instruction in the templates. All cases are validated to be arrays before passed to the templates.

**Comment by ghoneycutt** [comment]
Looks good. Also need to update Modulefile and metadata.json which both reference the version of stdlib

**Comment by ghoneycutt** [comment]
I'll take that.

**Comment by ghoneycutt** [comment]
@Phil-Friderici rebased and squashed the minor change into your commit in PR #71

**Pull request closed without merging**
