### PR TITLE
manage /dev/log socket on el7

### PR DESCRIPTION
**Pull request by joshuabaird**
Manages ```/dev/log``` on EL7 systems.

### CODE REVIEW

**Comment by joshuabaird** [comment]
Ok - so I hate using ```exec``` resources, but I don't really know how else to handle this.

@ghoneycutt thoughts?

**Comment by ghoneycutt** [comment]
This is a great fix! I'll get the README and spec tests updated.

**Comment by joshuabaird** [comment]
@ghoneycutt Think you will have time to get this released soon?

**Comment by ghoneycutt** [comment]
@joshuabaird I squashed your commits and add some for spec tests in PR #97 

Thanks!

**Pull request closed without merging**
